accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

facebook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', include('posts.urls')),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/like/', views.like, name='like'),
]

posts/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_posts')

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', )

accounts/views.py
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }

    return render(request, 'accounts/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

posts/views.py
import re

from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse

from .forms import PostForm
from .models import Post


def index(request):
    context = {
        'posts': Post.objects.all(),
    }
    return render(request, 'posts/index.html', context)


def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()

    context = {
        'form': form
    }

    return render(request, 'posts/form.html', context)


def like(request, id):
    requested_html = re.search(r'^text/html', request.META.get('HTTP_ACCEPT'))
    if not requested_html:
        post = get_object_or_404(Post, id=id)
        user = request.user
        if post.like_users.filter(id=user.id):
            post.like_users.remove(user)
            is_like = False
        else:
            post.like_users.add(user)
            is_like = True

        context = {
            'is_like': is_like,
            'like_users': post.like_users.count(),
        }

        return JsonResponse(context)
    else:
        raise ValueError('This request needs ajax only.')

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit">
  </form>
{% endblock %}

facebook/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  </head>
  <body>
    {% if user.is_authenticated %}
      <p>{{user.username}}</p>
      <a href="{% url 'accounts:logout' %}">Logout</a>
      <a href="{% url 'posts:create' %}">Write</a>
    {% else %}
      <a href="{% url 'accounts:signup' %}">Signup</a>
      <a href="{% url 'accounts:login' %}">Login</a>
    {% endif %}
    {% block body %}
    {% endblock %}
  </body>
</html>

posts/templates/posts/form.html
{% extends 'base.html' %}

{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
  </form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block body %}
  <h1>Index</h1>
  {% for post in posts %}
    <p>{{post.user.username}}</p>
    <p>{{post.title}}</p>
    <p><span id="count-{{post.id}}">{{post.like_users.count}} user</span> liked this post</p>
    {% if user in post.like_users.all %}
      <p class="like" data-id="{{post.id}}">🤍</p>
    {% else %}
      <p class="like" data-id="{{post.id}}">❤️</p>
    {% endif %}
    <hr>
  {% endfor %}

  <script>
    const likeBtns = document.querySelectorAll('.like')

    likeBtns.forEach((btn) => {
      btn.addEventListener('click', (e) => {
        const postId = e.target.dataset.id

        axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = 'X-CSRFToken'

        axios.post(`/posts/${postId}/like/`)
            .then((res) => {
              if (res.data.is_like) {
                e.target.innerText = '🤍'
              } else {
                e.target.innerText = '❤️'
              }

              const likeUsers = res.data.like_users
              const likeSpan = document.querySelector(`#count-${postId}`)

              if (likeUsers >= 2) {
                likeSpan.innerText = `${likeUsers} users`
              } else {
                likeSpan.innerText = `${likeUsers} user`
              }
            })
            .catch((err) => {
              console.log(err)
            })
      })
    })
  </script>
{% endblock %}